"""Initial Migration

Revision ID: 3b58e68abc55
Revises: 
Create Date: 2022-05-09 21:47:44.312388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b58e68abc55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'users', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'pitch_id')
    # ### end Alembic commands ###
